name: LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: main
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          root_file: main.tex
          working_directory: HW1

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: HW
          path: |
            main.pdf
